# Generated by Django 3.1.2 on 2020-11-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='favorites',
            field=models.ManyToManyField(related_name='liked_books', to='login.User'),
        ),
    ]
