# Generated by Django 3.1.2 on 2020-11-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='olduser', max_length=64),
            preserve_default=False,
        ),
    ]
